CREATE TABLE MyTable (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    UID VARCHAR(30) UNIQUE,
    Name VARCHAR(255)
);

INSERT INTO MyTable (UID, Name) VALUES (TO_BASE64(UNHEX(REPLACE(UUID(), '-',''))), 'John Smith');